snt_darmanko:
    resource: "@SNTDarmankoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: "@SNTDarmankoBundle/Controller/apiController.php"
    type:     annotation
